### ISSUE TITLE
Idea: use the wrapper component's query

### ISSUE THREAD

**Issue by Peeja** [anmonteiro/compassus#10]
As suggested on Slack:
1. Have the wrapper component implement `IQuery` and query for whatever it needs.
2. Rather than pass the factory and the route component's props to the wrapper, actually build the route component in the root component, then pass that _component_ into the wrapper as a (computed) prop. The parent of both the wrapper component and the route component is now the root.
3. Compose the wrapper's query and the route's query into the root component's query.

I believe this means that the wrapper query now has to live under a key, but that key might be private to Compassus, and the Compassus parser might be able to make that query act as if it were against the root.

**Comment by anmonteiro** [comment]
fixed 68d67309488fe2a5a0d80add7cb2c0a7e82c9cbb
