### ISSUE TITLE
Error message when route doesn't exist

### ISSUE THREAD

**Issue by julianwegkamp** [anmonteiro/compassus#14]
It would be nice to get a (better) error message when you go to a route (set-route!) that doesn't exist. Right now an TypeError is raised on line [55](https://github.com/compassus/compassus/blob/master/src/main/compassus/core.cljc#L55) since factory is nil.

Not a showstopper, but it confused me when I changed some routes but forgot to change a set-route! somewhere...

Minimal case:

```
(ns app.core
  (:require [om.next :as om :refer-macros [defui]]
            [om.dom :as dom]
            [compassus.core :as compassus]))

(declare app)

(defui A
  Object
  (render [this]
    ;; route :b isn't defined in routes
    (dom/button #js {:onClick #(compassus/set-route! app :b)} "B")))


(def routes {:index (compassus/index-route A)})

(defmulti read om/dispatch)

(def app
  (compassus/application
    {:routes routes
     :reconciler-opts {:state {}
                       :parser (om/parser {:read read})}}))

(compassus/mount! app (js/document.getElementById "app"))
```

**Comment by anmonteiro** [comment]
Thanks for the minimal case!

fixed fb2c8490d9119e6640ab72b472b8c16c95968fb8
