### ISSUE TITLE
Not forcing propagation of the `send`

### ISSUE THREAD

**Issue by agzam** [anmonteiro/compassus#15]
I've tried trivial examples where things are already in the state atom (on the client) and everything looks nice.

Then I tried to make something, where data should be fetched from a remote on each `c/set-route!`. So this is what I'm seeing:
- on initial `c/set-route!` for `c/index-route` everything works as expected:
  - you can see that dispatching `read` method being called twice: (first with `:target nil`, on the second pass with `:target :remote`)
- then, if there's an event that causes a different `c/set-route!` I don't seem to be able to find a way to force syncing with the remote
  - `read` is called only once with `:target nil`

for repro, you can check out this repo: 
https://github.com/agzam/trying-compassus

something seems to be wrong with calling `c/set-route!` with parameters, so for example if I remove :params here
https://github.com/agzam/trying-compassus/blob/master/src/cljs/sample_routing/colors.cljs#L67

it would try fetching data

**Comment by agzam** [comment]
I think I'm might be doing something wrong when I call `set-route!` with additional params
https://github.com/agzam/trying-compassus/blob/dan-branch/src/cljs/sample_routing/colors.cljs#L66

**Comment by agzam** [comment]
oh wow! I think I have figured it out... So for when `c/set-route!` called with 3d param it does not do `:queue true` by default anymore. So, it needs to be set explicitly. in that specific case 
at: https://github.com/agzam/trying-compassus/blob/master/src/cljs/sample_routing/colors.cljs#L67 it should be like:
`{:queue? true :params {:route-params {:color-id (str color-id)}}}`

**Comment by anmonteiro** [comment]
@agzam definitely a Compassus bug, thanks for figuring it out!

**Comment by anmonteiro** [comment]
fixed c44e2dd4af8822b00beed6836c404877b3536373
