### ISSUE TITLE
"Unable to resolve symbol: will-mount in this context" Error when running on om alpha48

### ISSUE THREAD

**Issue by livtanong** [anmonteiro/compassus#28]
```
clojure.lang.ExceptionInfo: Unable to resolve symbol: will-mount in this context
    file: "compassus/core.cljc"
    line: 50
```

Not an issue when i switch to om 47.

**Comment by anmonteiro** [comment]
[this commit](https://github.com/omcljs/om/commit/4be516efa584fb382fdfd87bd3b4a12fe102bede) in Om makes `ui` and `defui` create `defrecord`s in Clojure, which do not have access to local scope. I'm aware of this issue and have been thinking about what a potential fix might look like.

**Comment by anmonteiro** [comment]
fixed https://github.com/compassus/compassus/commit/4f4f413895afc317dac9b9526e42b21836ab6ff8
