### ISSUE TITLE
Allow Wrapper Queries

### ISSUE THREAD

**Issue by alexanderkiel** [anmonteiro/compassus#3]
The application accepts a wrapper component for common presentation logic. Currently this wrapper component can't have queries because they are simply not used in the query of the root component.

In my wrapper component I like to show the current signed-in user. To be able to do this, I need a query. So queries of the wrapper component should be included in the query of the root component.

**Comment by anmonteiro** [comment]
this has been addressed in b63876a806bb03b3e462754136bfcd24fdf2001b.
You can use the `compassus.core/query` mixin to add a query for your wrapper.
Also, the wrapper has been removed and is now replaced by a `wrap-render` mixin. You can even compose several of them!

**Comment by alexanderkiel** [comment]
Thanks! Works really good.
