### ISSUE TITLE
`compassus.core/application` should accept a `:reconciler` option

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/compassus#7]
The idea would be to simply pass an already assembled reconciler to Compassus, instead of passing a `:reconciler-opts` map.

The only problem I foresee would be constructing the parser, where 2 solutions come to mind:
1. provide a `compassus.core/parser` function that receives the user parser or the read/mutate functions instead of passing a `om.next/parser` directly to the `:parser` key
2. because of the dynamic nature of JavaScript, we can `set!` fields in the Om Next reconciler, so we could actually replace the user provided parser with the Compassus route-aware parser.

Feedback on 1. vs 2. appreciated

**Comment by livtanong** [comment]
If the problem is the setting of fields, and reconcilers are records, then couldn't you just assoc the necessary fields into the extant reconciler?

**Comment by anmonteiro** [comment]
the problem with that is that, since records are immutable, the Compassus reconciler wouldn't be the same that a user would hold in a var, for example.

**Comment by livtanong** [comment]
That's true. 
1. How about placing it in an atom? 
2. But then again the only reason the user would care about the var is for debugging with the repl. If that is true, why not have a function to return the reconciler that compassus is using? It wouldn't be all that different from om normalizing an initial database, and requiring us to use `(om/app-state reconciler)` for getting the true current app-state.

**Comment by anmonteiro** [comment]
1. I don't like it because it means we require users to do stuff just because we're going to modify it.
2. we already provide such a function. Also, it is common to use the reconciler to perform transactions with fine-grained control.

Anyway, thanks for the ideas. It might not seem at first, but it's really helpful. The real problem here might be that I'm searching for a solution that might not exist. At least without making any tradeoffs (e.g. 1.) :)

**Comment by livtanong** [comment]
1. I figured you wouldn't like this :P 
2. d'oh!

My pleasure, anything I can do to help. :D

**Comment by anmonteiro** [comment]
fixed 253874ed91a2c14948663cfc713d2c6f60fdd4d4
